---
- name: Destroy VM {{ vm_instance_name }}
  virt:
    command: destroy
    name: "{{ vm_instance_name }}"
  ignore_errors: yes

- name: Undefine VM {{ vm_instance_name }}
  virt:
    command: undefine
    name: "{{ vm_instance_name }}"
  ignore_errors: yes

- name: Delete disks belongs to instance {{ vm_instance_name }}
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "/var/lib/libvirt/images/{{ vm_instance_name }}.qcow2"
  - "/var/lib/libvirt/images/{{ vm_instance_name }}-ocs.qcow2"
  - "/var/lib/libvirt/images/{{ vm_instance_name }}.ign"
