---
- name: Create system user
  import_tasks: create-sytem-user.yaml
  vars:
    user_name: grafana

- name: "Install service"
  import_tasks: install-container-service.yml
  vars:
    service_name: "grafana"
    service_description: "Grafana"
    container_name: "grafana"
    container_image: 'grafana/grafana'
    container_args: ""
    podman_args: "--user {{ return_user.uid }} --net host -e 'GF_SERVER_ROOT_URL=http://homer.bohne.io' -e 'GF_SECURITY_ADMIN_PASSWORD=Ju3uc3aejeshiexi' -v /opt/grafana:/var/lib/grafana:z"
