#!/usr/bin/env ansible-playbook
---
- name: Install node-exporter.service
  import_tasks: install-container-service.yml
  vars:
    service_name: "node-exporter"
    service_description: "Prometheus node-exporter"
    container_name: "node-exporter"
    container_image: 'quay.io/prometheus/node-exporter'
    container_args: "--path.rootfs=/host"
    podman_args: "--net host --pid host -v '/:/host:ro,rslave'"